name: EfficientHomes
main: org.puretie.EfficientHomes
version: 1.0
commands:
  efficienthome:
    aliases: [ehome, eh, home]
    description: Takes you home.
  efficientsethome:
    aliases: [sethome, sh]
    description: Makes your new home!
  efficienthomes:
   aliases: [homes]
   description: Lists homes.